import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { X, Download, Copy, Check, FileCode, Printer } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, result }) => {
  const [copiedType, setCopiedType] = useState<string | null>(null);

  if (!isOpen) return null;

  const markdownContent = `# CS Research Analysis: ${result.paper.title}
*Authors: ${result.paper.authors.join(', ')} | ${result.paper.venue || ''} (${result.paper.year})*
*URL: ${result.paper.url}*

## 1. CORE CONCEPT EXTRACTION
**Word count:** ${result.coreConcept.wordCount || 250} words

### Problem Statement
${result.coreConcept.problemStatement}

### Primary Methodology
${result.coreConcept.primaryMethodology}

### Mathematical & Algorithmic Breakthroughs
${result.coreConcept.mathematicalBreakthroughs}

### Accessible Synthesis
${result.coreConcept.fullSummary}

---

## 2. ARCHITECTURAL FLOWCHART (Mermaid.js)
[FLOWCHART]

\`\`\`mermaid
${result.flowchart.mermaidCode}
\`\`\`

---

## 3. FUTURE WORK & INTERNSHIP OPPORTUNITIES
${result.studentOpportunities.map((opp, idx) => `
### Project ${idx + 1}: ${opp.title} (${opp.difficulty})
- **Expected Contribution:** ${opp.expectedContribution}
- **Targeted Performance Metric:** ${opp.targetedPerformanceMetric}
- **Recommended Tech Stack:** ${opp.recommendedTechStack.join(', ')}
- **Timeline:** ~${opp.estimatedWeeks || 3} weeks
- **Resume Impact Bullet (STAR):**
  > ${opp.resumeBullet}
`).join('\n')}

---
*Generated by ScholarAgent Research System | Tokens: ${result.tokenStats.totalTokens} / 25,000*
`;

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.paper.title.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase().slice(0, 40)}_analysis.md`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.paper.title.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase().slice(0, 40)}_data.json`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(markdownContent);
    setCopiedType('md');
    setTimeout(() => setCopiedType(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fadeIn">
      <div className="w-full max-w-xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/50">
          <h3 className="text-sm font-semibold text-slate-100">Export Research Analysis</h3>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-slate-200 rounded-lg hover:bg-slate-800 transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content options */}
        <div className="p-6 space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-3 p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-cyan-500/40 text-left transition group"
            >
              <div className="p-2 rounded-lg bg-cyan-500/10 text-cyan-400 group-hover:scale-110 transition-transform">
                <Download className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-200">Markdown (.md)</div>
                <div className="text-[11px] text-slate-400">Complete analysis with [FLOWCHART]</div>
              </div>
            </button>

            <button
              onClick={handleDownloadJSON}
              className="flex items-center gap-3 p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-cyan-500/40 text-left transition group"
            >
              <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 group-hover:scale-110 transition-transform">
                <FileCode className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-200">Structured JSON</div>
                <div className="text-[11px] text-slate-400">Raw nodes, stats & opportunities</div>
              </div>
            </button>
          </div>

          <div className="pt-2 flex items-center justify-between border-t border-slate-800">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-2 px-4 py-2 text-xs font-medium bg-slate-800 hover:bg-slate-750 text-slate-200 rounded-lg border border-slate-700 transition"
            >
              {copiedType === 'md' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedType === 'md' ? 'Copied Markdown' : 'Copy Markdown'}
            </button>

            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 px-4 py-2 text-xs font-medium bg-slate-800 hover:bg-slate-750 text-slate-200 rounded-lg border border-slate-700 transition"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
